version: '3.8'

services:

  service-registry:
    image: ad-library/spring310-service-registry:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - my-network

  course-service:
    image: ad-library/spring310-course-service:0.0.1-SNAPSHOT
    ports:
      - "8181:8080"
    networks:
      - my-network
    depends_on:
      - service-registry
    environment:
      eureka.client.service-url.defaultZone: http://service-registry:8761/eureka/

  student-service:
    image: ad-library/spring310-student-service:0.0.1-SNAPSHOT
    ports:
      - "8182:8080"
    networks:
      - my-network
    depends_on:
      - service-registry
    environment:
      eureka.client.service-url.defaultZone: http://service-registry:8761/eureka/

networks:
  my-network: