---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-world-ns

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: student-service
  name: student-service
  namespace: spring-world-ns
spec:
  ports:
    - port: 8182
      protocol: TCP
      targetPort: 8182
  selector:
    app: student-service
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: student-service
  name: student-service
  namespace: spring-world-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  strategy: {}
  template:
    metadata:
      labels:
        app: student-service
    spec:
      volumes:
        - name: application-config
          configMap:
            name: spring-with-k8s-config
      containers:
      - name: student-service
        image: ad-library/spring310-student-service:0.0.1-SNAPSHOT
        volumeMounts:
          - name: application-config
            mountPath: "/deployments/config"
            readOnly: true